### PR TITLE
okeygroup4added

### PR DESCRIPTION
**Pull request by okeynweke**
Please kindly review.
Thanks

### CODE REVIEW

**Review by fidelosa — APPROVED** [review]
Looks great

**Review by anthonynwanne — CHANGES_REQUESTED** [review]
system analysis commands only

**Review by estherakinwumi — APPROVED** [review]
reviewed

**Review by estherakinwumi — APPROVED** [review]
reviewed

**Comment by okeynweke** [comment]
> 

Noted

**Pull request closed without merging**
