### PR TITLE
my system analysis

### PR DESCRIPTION
**Pull request by fidelosa**
Engr. Elvis, this is for your approval.

### CODE REVIEW

**Review by rnfor-pro — APPROVED** [review]

**Comment by rnfor-pro** [comment]
great job

**Comment by fidelosa** [comment]
team members pls review

**Review by Big-Zaza — APPROVED** [review]
Great script

**Review by estherakinwumi — COMMENTED** [review]
for your approval

**Review by estherakinwumi — APPROVED** [review]
reviewed

**Review by anthonynwanne — APPROVED** [review]

**Comment by anthonynwanne** [comment]
done

**Pull request merged**
