### PR TITLE
System analysis script

### PR DESCRIPTION
**Pull request by Big-Zaza**
Simple script to perform system analysis.
Please sir kindly approve

### CODE REVIEW

**Comment by rnfor-pro** [comment]
Awesome

**Review by rnfor-pro — APPROVED** [review]

**Review by anthonynwanne — APPROVED** [review]
amazing

**Review by fidelosa — APPROVED** [review]
Looks great

**Review by estherakinwumi — COMMENTED** [review]
reveiwed

**Review by estherakinwumi — COMMENTED** [review]
reviewed

**Review by estherakinwumi — COMMENTED** [review]
reviewed

**Review by estherakinwumi — COMMENTED** [review]
reviewed

**Review by estherakinwumi — COMMENTED** [review]
reviewed.........

**Review by estherakinwumi — COMMENTED** [review]
approved

**Review by estherakinwumi — COMMENTED** [review]
reviewd

**Review by estherakinwumi — COMMENTED** [review]
reviewed

**Review by estherakinwumi — COMMENTED** [review]
reviewed

**Pull request merged**
