### PR TITLE
myshellscript

### PR DESCRIPTION
**Pull request by anthonynwanne**
kindly review and approve

### CODE REVIEW

**Comment by anthonynwanne** [comment]
treat

**Comment by anthonynwanne** [comment]
treat

**Comment by anthonynwanne** [comment]
close

**Comment by anthonynwanne** [comment]
treat

**Comment by anthonynwanne** [comment]
treat

**Review by Big-Zaza — APPROVED** [review]
I think this script is an excellent one.

**Review by fidelosa — APPROVED** [review]
Great

**Review by estherakinwumi — APPROVED** [review]
reviewed

**Review by estherakinwumi — APPROVED** [review]
reviewed

**Pull request merged**
