### PR TITLE
Kelechi's sys analyScript

### PR DESCRIPTION
**Pull request by Kellymooreng**
Please see my script.

### CODE REVIEW

**Review by rnfor-pro — APPROVED** [review]

**Comment by rnfor-pro** [comment]
I have approved your work I think you need 2 more engineers to review according to your configurations

**Review by anthonynwanne — APPROVED** [review]
amazing

**Review by fidelosa — APPROVED** [review]
Great script

**Review by estherakinwumi — APPROVED** [review]
reviewed

**Comment by Kellymooreng** [comment]
Thanks

**Pull request merged**
